site_name: {{cookiecutter.github_username}}/{{cookiecutter.project_name}}
repo_url: {{cookiecutter.url}}
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
plugins:
  - search
  - mkdocstrings
