[tool.commitizen]
version = "{{cookiecutter.version}}"
version_files = ["src/{{cookiecutter.package_name}}/_version.py"]
changelog_file = "docs/changelog.md"
update_changelog_on_bump = true
tag_format = "v$minor.$major.$patch$prerelease"