# Initial template: https://docs.github.com/en/actions/guides/building-and-testing-python#starting-with-the-python-workflow-template

name: Python package

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r devtools/requirements-dev.txt

    - name: Test with pytest
      run: |
        pytest
    # Run linters (black, flake8, isort) as configured with pre-commit.        
    - name: Run pre-commit hooks
      run: |
        pre-commit install -c devtools/pre-commit-config.yaml
        pre-commit run -a
    

