name: Build documentation wit mkdocs-material

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: | 
          pip install mkdocs-material
          pip install mkdocstrings
      - run: mkdocs gh-deploy --force