repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      args: # arguments to configure black
        - --line-length=88
        - --include='\.pyi?$'
        # these folders wont be formatted by black
        - --exclude="""\.git|
          \data|
          \.devtools|
          \.github|
          \.__pycache__|
          \.tox|
          \.venv"""
      language_version: python3
-   repo: https://gitlab.com/pycqa/flake8
    rev: master
    hooks:
    - id: flake8
      language_version: python3
      args: 
        - "--max-line-length=88"
        - "--max-complexity=18"
        - "--select=B,C,E,F,W,T4,B9"
        # these are errors that will be ignored by flake8
        # check out their meaning here
        # https://flake8.pycqa.org/en/latest/user/error-codes.html
        - "--ignore=E203,E266,E501,W503,F403,F401,E402"
- repo: https://github.com/asottile/seed-isort-config
  rev: master
  hooks:
  - id: seed-isort-config
- repo: https://github.com/pre-commit/mirrors-isort
  rev: master
  hooks:
  - id: isort